version: "3.8"
services: 
    api:
        container_name: secret-message-api
        environment:
            - SERVER_TOKEN=your_token
            - RELESE_TYPE=local
            - MONGO_URI=mongodb://mongo:27017/secret-message
            - PORT=3000
        image: frankoslaw/secret-message
        restart: always
        build: .
        ports:
            - "3001:3000"
        links:
            - mongo
        depends_on:
            - mongo
          
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27018:27017'